.TH MPE_CreateRoundRobinComm 3 "4/23/2018" " " ""
.SH NAME
MPE_CreateRoundRobinComm \-  Create a round-robin mapped communicator for  all processes.  
.SH SYNOPSIS
.nf
int MPE_CreateRoundRobinComm( MPI_Comm comm, MPI_Comm *rrcomm, int *nnodes )
.fi
.SH INPUT PARAMETER
.PD 0
.TP
.B comm 
- Communicator of processes
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B rrcomm 
- New communicator where processes are mapped in a round-robin
fashion between nodes
.PD 1
.PD 0
.TP
.B nnodes   
- My node number
.PD 1

