.TH TextFileReadDebug 3 "1/3/2019" " " ""
.SH NAME
TextFileReadDebug \-  Set debugging options for TextFile routines 
.SH SYNOPSIS
.nf
int TextFileReadDebug(int v)
.fi
.SH INPUT PARAMETER
.PD 0
.TP
.B v 
- If nonzero, turns on verbose output to stdout
.PD 1

.SH NOTES
This routine is for use by developers of TextFile and experts.  Understanding
the output requires access to the source code for TextFile.

