.TH topoMethod_t 3 "4/23/2018" " " ""
.SH NAME
topoMethod_t \-  Available methods for determining topology 
.SH SYNOPSIS
.nf
typedef enum { TOPO_DEFAULT, TOPO_GENERIC, TOPO_CRAY_RCA, TOPO_BGQ_MPIX,
TOPO_MPISPLIT, TOPO_NODENAME,
TOPO_HWLOC, TOPO_GETCPU, TOPO_GETAFFINITY,
TOPO_DEBUG } topoMethod_t;
.fi
